title:             Fath Tips
email:             ahmedfathelbab@gmail.com
description:       Not a big fan of leaving comfort zones. I like mine. Hope you like it too.
author:             Ahmed Fathelbab
baseurl:            "fathelbaba.github.io"
url:                "https://ahmedfathelbab.me"

# Social Profiles
twitter_username:   afat7elbab
github_username:    afathelbab
facebook_username:  ahmed.fathelbab
instagram_username:  afat7elbab
linkedin_username: fathelbab

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-213791447-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Theme
theme: jekyll-theme-clean-blog
