title:             Ahmed Fathelbab
email:             ahmedfathelbab@gmail.com
description:        My Blog
author:             Ahmed Fathelbab
baseurl:            "/fathelbaba.github.io"
url:                "https://ahmedfathelbab.me"

# Social Profiles
twitter_username:   afat7elbab
github_username:    afathelbab
facebook_username:  ahmed.fathelbab
instagram_username:  afat7elbab
linkedin_username: fathelbab

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
