title:             Fath Tips
email:             ahmedfathelbab@gmail.com
description:       Leaving my comfort zone is not my thing. However, I can invite you to it!
author:             Ahmed Fathelbab
baseurl:            "/fathelbaba.github.io"
url:                "https://ahmedfathelbab.me"

# Social Profiles
twitter_username:   afat7elbab
github_username:    afathelbab
facebook_username:  ahmed.fathelbab
instagram_username:  afat7elbab
linkedin_username: fathelbab

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Theme
theme: jekyll-theme-clean-blog
